# Shougo-san's plugins {{{
# ---------------------------------------------------------------------------------------------------
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'
hook_add = '''
 if has('mac')
    let g:deoplete#sources#jedi#python_path = '/usr/bin/python'
 elseif has('unix')
    let g:deoplete#sources#jedi#python_path = $HOME . '/.pyenv/shims/python'
 endif
'''

[[plugins]]
repo = 'Shougo/neoyank.vim'

[[plugins]]
repo = 'Shougo/vimfiler'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

# }}}

# Common {{{
# ---------------------------------------------------------------------------------------------------
[[plugins]]
repo = 'Shougo/neco-syntax'

[[plugins]]
repo = 'itchyny/vim-cursorword'

[[plugins]]
repo = 'thinca/vim-template'
# }}}

# Filer {{{
# ---------------------------------------------------------------------------------------------------
[[plugins]]
repo = 'scrooloose/nerdtree'
# }}}

# Appearance {{{
# ---------------------------------------------------------------------------------------------------
[[plugins]]
repo = 'zeis/vim-kolor'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'beikome/cosme.vim'

# }}}

# Run {{{
# ---------------------------------------------------------------------------------------------------
[[plugins]]
repo = 'w0rp/ale'

# }}}

# ColorScheme {{{
# ---------------------------------------------------------------------------------------------------
[[plugins]]
repo = 'cocopon/pgmnt.vim'
# }}}
