# Shougo-san's plugins {{{
# ---------------------------------------------------------------------------------------------------
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/neoyank.vim'

[[plugins]]
repo = 'Shougo/vimfiler'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

# }}}

# Common {{{
# ---------------------------------------------------------------------------------------------------
[[plugins]]
repo = 'Shougo/neco-syntax'

[[plugins]]
repo = 'itchyny/vim-cursorword'

[[plugins]]
repo = 'thinca/vim-template'

# }}}


# Filer {{{
# ---------------------------------------------------------------------------------------------------
[[plugins]]
repo = 'scrooloose/nerdtree'
# }}}

# Appearance {{{
# ---------------------------------------------------------------------------------------------------
[[plugins]]
repo = 'itchyny/lightline.vim'

# }}}

# Color scheme {{{
# ---------------------------------------------------------------------------------------------------
[[plugins]]
repo = 'zeis/vim-kolor'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'sonjapeterson/1989.vim'

[[plugins]]
repo = 'beikome/cosme.vim'

[[plugins]]
repo = 'sonph/onehalf'

[[plugins]]
repo = 'jnurmine/Zenburn'

[[plugins]]
repo = 'dracula/vim'

[[plugins]]
repo = 'NLKNguyen/papercolor-theme'

[[plugins]]
repo = 'chriskempson/base16-vim'
# }}}

# Linter {{{
# ---------------------------------------------------------------------------------------------------
[[plugins]]
repo = 'w0rp/ale'
# }}}

# Run {{{
# ---------------------------------------------------------------------------------------------------
[[plugins]]
repo = 'thinca/vim-quickrun'
# }}}

# Create ColorScheme {{{
# ---------------------------------------------------------------------------------------------------
[[plugins]]
repo = 'cocopon/svss.vim'

[[plugins]]
repo = 'cocopon/pgmnt.vim'

#}}}
