# Common {{{
# ---------------------------------------------------------------------------------------------------
[[plugins]]
repo = 'Shougo/neco-syntax'

[[plugins]]
repo = 'itchyny/vim-cursorword'

[[plugins]]
repo = 'thinca/vim-template'

# }}}

# Edit {{{
# ---------------------------------------------------------------------------------------------------
[[plugins]]
repo = 'tyru/caw.vim'

# }}}

# Filer {{{
# ---------------------------------------------------------------------------------------------------
[[plugins]]
repo = 'scrooloose/nerdtree'
# }}}

# Appearance {{{
# ---------------------------------------------------------------------------------------------------
[[plugins]]
repo = 'itchyny/lightline.vim'

#[[plugins]]
#repo = 'vim-airline/vim-airline'

# }}}

# Color Scheme {{{
# ---------------------------------------------------------------------------------------------------
[[plugins]]
repo = 'zeis/vim-kolor'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'sonjapeterson/1989.vim'

[[plugins]]
repo = 'beikome/cosme.vim'

[[plugins]]
repo = 'sonph/onehalf'

[[plugins]]
repo = 'jnurmine/Zenburn'

[[plugins]]
repo = 'dracula/vim'

[[plugins]]
repo = 'NLKNguyen/papercolor-theme'

[[plugins]]
repo = 'chriskempson/base16-vim'
# }}}

# Linter {{{
# ---------------------------------------------------------------------------------------------------
[[plugins]]
repo = 'w0rp/ale'
# }}}

# Run {{{
# ---------------------------------------------------------------------------------------------------
[[plugins]]
repo = 'thinca/vim-quickrun'
# }}}

# Syntax Highlight {{{
# ---------------------------------------------------------------------------------------------------
[[plugins]]
repo = 'sirtaj/vim-openscad'


# Create ColorScheme {{{
# ---------------------------------------------------------------------------------------------------
[[plugins]]
repo = 'cocopon/svss.vim'

[[plugins]]
repo = 'cocopon/pgmnt.vim'

[[plugins]]
repo = 'gko/vim-coloresque'

#}}}
